#!/bin/bash

set -u
set -e

readonly NOTES_FILE=~/.config/rofi/rofinotes

if [[ ! -a "${NOTES_FILE}" ]] || [[ ! -s "${NOTES_FILE}" ]]; then
    echo "Exit" >> "${NOTES_FILE}"
fi

run=true

function get_notes()
{
    cat ${NOTES_FILE}
}

function main()
{
    local all_notes="$(get_notes)"

    local note=$( (echo "${all_notes}")  | rofi -dmenu -p "Note:")
    local matching=$( (echo "${all_notes}") | grep "^${note}$")


    if [[ ${note} == "Exit" ]] then
	   run=false 
    elif [[ ${note} == "----------" ]] then
	   echo "only cli can see tis lol"
    elif [[ -n "${matching}" ]]; then
        local new_notes=$( (echo "${all_notes}")  | grep -v "^${note}$" )
	echo "${new_notes}" > "${NOTES_FILE}"
    else
        local new_notes=$( (echo -e "${all_notes}\n${note}") | grep -v "^$")
	echo "${new_notes}" > "${NOTES_FILE}"
    fi

    #echo "${new_notes}" > "${NOTES_FILE}"
}
while $run; do
    main
done
